(()=>{
  'use strict';
  const Auth=globalThis.MijnLoopLocalAuth,root=document.getElementById('admin-root'),toastEl=document.getElementById('toast');let toastTimer,users=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=v=>v?new Date(v).toLocaleString('nl-NL'):'—';
  function toast(t){clearTimeout(toastTimer);toastEl.textContent=t;toastEl.classList.add('visible');toastTimer=setTimeout(()=>toastEl.classList.remove('visible'),4500);}
  function modal(html){document.querySelector('.admin-modal-overlay')?.remove();const o=document.createElement('div');o.className='modal-overlay admin-modal-overlay';o.innerHTML=`<section class="modal wide">${html}</section>`;document.body.append(o);o.addEventListener('click',e=>{if(e.target===o)o.remove();});return o;}
  function setup(){root.innerHTML=`<section class="admin-panel admin-narrow"><div class="eyebrow">Eerste installatie</div><h1>Maak de beheerder aan</h1><p>Deze beheerder wordt centraal opgeslagen en werkt daarna op al je apparaten.</p><form id="setup"><div class="form-error"></div><label>Naam<input name="displayName" required></label><label>Gebruikersnaam<input name="username" required></label><label>Wachtwoord<input name="password" type="text" required></label><label>Herhaal wachtwoord<input name="confirm" type="text" required></label><button class="btn primary" type="submit">Beheerder aanmaken</button></form></section>`;}
  function login(){root.innerHTML=`<section class="admin-panel admin-narrow"><div class="eyebrow">MijnLoop Beheer</div><h1>Beheerder inloggen</h1><form id="admin-login"><div class="form-error"></div><label>Gebruikersnaam<input name="username" required></label><label>Wachtwoord<input name="password" type="password" required></label><button class="btn primary" type="submit">Inloggen</button></form><p class="admin-note mt">Accounts en sportdata worden centraal gesynchroniseerd via Supabase, zonder Supabase Auth.</p></section>`;}
  async function dashboard(){users=await Auth.listUsers();root.innerHTML=`<section class="admin-panel"><div class="admin-heading"><div><div class="eyebrow">Centraal accountbeheer</div><h1>Gebruikersbeheer</h1><p>Deze accounts zijn op alle apparaten hetzelfde.</p></div><div class="button-row"><button class="btn primary" data-action="new">Gebruiker toevoegen</button><button class="btn" data-action="logout">Uitloggen</button></div></div><div class="admin-users">${users.map(u=>`<article class="admin-user"><div><strong>${esc(u.displayName)}</strong><p>@${esc(u.username)} · ${u.role==='admin'?'Beheerder':'Gebruiker'} · ${u.active?'Actief':'Geblokkeerd'}</p></div><div class="button-row"><button class="btn compact" data-action="view" data-id="${u.id}">Inzien</button><button class="btn compact" data-action="edit" data-id="${u.id}">Bewerken</button><button class="btn compact" data-action="password" data-id="${u.id}">Wachtwoord wijzigen</button><button class="btn compact" data-action="toggle" data-id="${u.id}" data-active="${u.active?'1':'0'}">${u.active?'Blokkeren':'Activeren'}</button><button class="btn danger compact" data-action="delete" data-id="${u.id}">Verwijderen</button></div></article>`).join('')}</div></section>`;}
  async function render(){try{await Auth.connect();if(!Auth.hasUsers())return setup();if(!Auth.currentAdmin())return login();await dashboard();}catch(e){root.innerHTML=`<section class="admin-panel admin-narrow"><h1>Geen verbinding</h1><p>${esc(e.message)}</p><button class="btn" onclick="location.reload()">Opnieuw proberen</button></section>`;}}
  function user(id){return users.find(x=>x.id===id);}
  async function view(id){const u=user(id);if(!u)return;const s=await Auth.adminState(id),p=s?.profile||{},w=Array.isArray(s?.workouts)?s.workouts:[];modal(`<div class="modal-head"><div><div class="eyebrow">Gebruiker inzien</div><h2>${esc(u.displayName)}</h2></div><button class="btn" data-close>Sluiten</button></div><div class="admin-detail-grid"><div><span>Gebruikersnaam</span><strong>${esc(u.username)}</strong></div><div><span>Wachtwoord</span><strong>${esc(u.passwordPlain)}</strong></div><div><span>Rol</span><strong>${u.role==='admin'?'Beheerder':'Gebruiker'}</strong></div><div><span>Status</span><strong>${u.active?'Actief':'Geblokkeerd'}</strong></div><div><span>Doel</span><strong>${esc(p.goal||'—')}</strong></div><div><span>Doeldatum</span><strong>${esc(p.raceDate||'—')}</strong></div><div><span>Trainingen</span><strong>${w.length}</strong></div><div><span>Laatst gewijzigd</span><strong>${esc(fmt(u.updatedAt))}</strong></div></div>`);}
  function edit(id){const u=user(id);if(!u)return;modal(`<div class="modal-head"><div><div class="eyebrow">Account bewerken</div><h2>${esc(u.displayName)}</h2></div><button class="btn" data-close>Sluiten</button></div><form id="edit" data-id="${id}"><div class="form-error"></div><div class="form-grid"><label>Naam<input name="displayName" value="${esc(u.displayName)}" required></label><label>Gebruikersnaam<input name="username" value="${esc(u.username)}" required></label><label>Wachtwoord<input name="password" type="text" value="${esc(u.passwordPlain)}" required></label><label>Rol<select name="role"><option value="user" ${u.role==='user'?'selected':''}>Gebruiker</option><option value="admin" ${u.role==='admin'?'selected':''}>Beheerder</option></select></label><label>Status<select name="active"><option value="1" ${u.active?'selected':''}>Actief</option><option value="0" ${!u.active?'selected':''}>Geblokkeerd</option></select></label></div><button class="btn primary" type="submit">Opslaan</button></form>`);}
  function create(){modal(`<div class="modal-head"><div><div class="eyebrow">Nieuw account</div><h2>Gebruiker toevoegen</h2></div><button class="btn" data-close>Sluiten</button></div><form id="create"><div class="form-error"></div><div class="form-grid"><label>Naam<input name="displayName" required></label><label>Gebruikersnaam<input name="username" required></label><label>Wachtwoord<input name="password" type="text" required></label><label>Rol<select name="role"><option value="user">Gebruiker</option><option value="admin">Beheerder</option></select></label></div><button class="btn primary" type="submit">Account aanmaken</button></form>`);}
  document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,d=new FormData(f),err=f.querySelector('.form-error');try{if(f.id==='setup'){if(d.get('password')!==d.get('confirm'))throw new Error('De wachtwoorden zijn niet hetzelfde.');await Auth.bootstrapAdmin({displayName:d.get('displayName'),username:d.get('username'),password:d.get('password')});toast('Beheerder aangemaakt.');await render();}else if(f.id==='admin-login'){await Auth.adminLogin(d.get('username'),d.get('password'));await render();}else if(f.id==='create'){await Auth.createUser({displayName:d.get('displayName'),username:d.get('username'),password:d.get('password'),role:d.get('role')});document.querySelector('.admin-modal-overlay')?.remove();toast('Account aangemaakt.');await dashboard();}else if(f.id==='edit'){const id=f.dataset.id,u=user(id);await Auth.updateUser(id,{displayName:d.get('displayName'),username:d.get('username'),role:d.get('role'),active:d.get('active')==='1'});if(String(d.get('password'))!==u.passwordPlain)await Auth.setPassword(id,d.get('password'));document.querySelector('.admin-modal-overlay')?.remove();toast('Account bijgewerkt.');await dashboard();}}catch(x){if(err)err.textContent=x.message;else toast(x.message);}});
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-action],[data-close]');if(!b)return;try{if(b.hasAttribute('data-close'))return document.querySelector('.admin-modal-overlay')?.remove();const a=b.dataset.action,id=b.dataset.id;if(a==='new')create();if(a==='logout'){await Auth.adminLogout();await render();}if(a==='view')await view(id);if(a==='edit')edit(id);if(a==='password'){const pw=prompt('Nieuw wachtwoord:',user(id)?.passwordPlain||'');if(pw!==null&&pw!==''){await Auth.setPassword(id,pw);toast('Wachtwoord gewijzigd.');await dashboard();}}if(a==='toggle'){await Auth.updateUser(id,{active:b.dataset.active!=='1'});await dashboard();}if(a==='delete'){if(confirm('Account en alle sportgegevens verwijderen?')){await Auth.deleteUser(id);await dashboard();}}}catch(x){toast(x.message);}});
  render();
})();
