(function(){
  'use strict';
  const root=document.getElementById('admin-root'),Auth=globalThis.MijnLoopLocalAuth;let toastTimer;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('visible'),4500);}
  function error(form,msg){const e=form.querySelector('.form-error');if(e)e.textContent=msg;else toast(msg);}
  async function disconnectStravaFor(userId){try{const c=Auth.adminIntegrationCredentials(userId),cfg=globalThis.SPORT_CONFIG;if(!c||!cfg?.supabaseUrl||!cfg?.supabasePublishableKey)return;await fetch(`${cfg.supabaseUrl}/functions/v1/strava`,{method:'POST',headers:{'Content-Type':'application/json','apikey':cfg.supabasePublishableKey,'X-Local-Account':c.accountId,'X-Local-Secret':c.secret},body:JSON.stringify({action:'disconnect'})});}catch{}}
  function download(text,type,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},2000);}
  function setup(){root.innerHTML=`<section class="admin-panel admin-narrow"><div class="eyebrow">Eerste keer</div><h1>Maak de lokale beheerder</h1><p>Dit account bestaat alleen in deze browser. Er is geen standaardwachtwoord en er wordt niets naar Supabase gestuurd.</p><form id="setup-form"><div class="form-error" role="alert"></div><label>Naam<input name="displayName" maxlength="60" placeholder="Jeremy" required></label><label>Gebruikersnaam<input name="username" autocomplete="username" placeholder="beheerder" required></label><label>Beheerderswachtwoord<input name="password" type="password" autocomplete="new-password" required></label><label>Herhaal wachtwoord<input name="confirm" type="password" autocomplete="new-password" required></label><button class="btn primary" type="submit">Beheer instellen</button></form><p class="admin-note mt">Wachtwoorden worden gehashd opgeslagen. Het bestaande wachtwoord is daarom later niet terug te lezen, maar je kunt het altijd resetten.</p></section>`;}
  function login(){root.innerHTML=`<section class="admin-panel admin-narrow"><div class="eyebrow">Beheer</div><h1>Inloggen als beheerder</h1><form id="admin-login"><div class="form-error" role="alert"></div><label>Gebruikersnaam<input name="username" autocomplete="username" required></label><label>Wachtwoord<input name="password" type="password" autocomplete="current-password" required></label><button class="btn primary" type="submit">Inloggen</button></form><p class="mt"><a href="./">Terug naar MijnLoop</a></p></section>`;}
  function dashboard(){const admin=Auth.currentAdmin(),users=Auth.listUsers();root.innerHTML=`<div class="admin-grid"><section class="admin-panel"><div class="admin-toolbar"><div><div class="eyebrow">Lokale accounts</div><h1>Gebruikersbeheer</h1></div><button class="btn" data-action="admin-logout">Uitloggen</button></div><p class="admin-note">Aangemeld als ${esc(admin.displayName)}. Accounts hieronder bestaan alleen op dit apparaat/browser.</p><div id="users">${users.map(userCard).join('')}</div></section><aside class="admin-panel"><h2>Nieuw account</h2><form id="create-user"><div class="form-error" role="alert"></div><label>Naam<input name="displayName" maxlength="60" required></label><label>Gebruikersnaam<input name="username" required></label><label>Startwachtwoord<input name="password" type="password" required></label><label>Rol<select name="role"><option value="user">Gebruiker</option><option value="admin">Beheerder</option></select></label><button class="btn primary" type="submit">Account aanmaken</button></form><div class="admin-separator"></div><h2>Lokale backup</h2><p class="admin-note">Exporteer accounts én sportgegevens om deze browser te kunnen herstellen of naar een ander apparaat te verplaatsen.</p><div class="button-row"><button class="btn compact" data-action="backup-export">Backup downloaden</button><button class="btn compact" data-action="backup-import">Backup importeren</button></div><input id="backup-file" type="file" accept="application/json,.json" hidden><div class="admin-separator"></div><p><a href="./">Open MijnLoop</a></p></aside></div>`;}
  function userCard(u){return `<div class="admin-user" data-id="${esc(u.id)}"><div><h3>${esc(u.displayName)}</h3><p>@${esc(u.username)} · ${u.role==='admin'?'Beheerder':'Gebruiker'} · <span class="admin-badge ${u.active?'':'off'}">${u.active?'Actief':'Geblokkeerd'}</span></p></div><div class="admin-user-actions"><button class="btn compact" data-action="reset-password" data-id="${esc(u.id)}">Wachtwoord resetten</button><button class="btn compact" data-action="toggle-user" data-id="${esc(u.id)}" data-active="${u.active?'1':'0'}">${u.active?'Blokkeren':'Activeren'}</button><button class="btn compact danger" data-action="delete-user" data-id="${esc(u.id)}">Verwijderen</button></div></div>`;}
  function render(){if(!Auth.hasUsers())return setup();if(!Auth.currentAdmin())return login();dashboard();}
  document.addEventListener('submit',async e=>{e.preventDefault();const f=e.target,fd=new FormData(f);try{if(f.id==='setup-form'){if(fd.get('password')!==fd.get('confirm'))throw new Error('De wachtwoorden zijn niet hetzelfde.');await Auth.bootstrapAdmin({displayName:fd.get('displayName'),username:fd.get('username'),password:fd.get('password')});toast('Beheerder aangemaakt. Log nu in.');render();}else if(f.id==='admin-login'){await Auth.adminLogin(fd.get('username'),fd.get('password'));render();}else if(f.id==='create-user'){await Auth.createUser({displayName:fd.get('displayName'),username:fd.get('username'),password:fd.get('password'),role:fd.get('role')});toast('Account aangemaakt.');render();}}catch(err){error(f,err.message);}});
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;try{if(action==='admin-logout'){Auth.adminLogout();render();return;}if(action==='reset-password'){const pw=Auth.generatePassword();if(!confirm('Wachtwoord van dit account resetten naar een nieuw tijdelijk wachtwoord?'))return;await Auth.setPassword(id,pw);const box=document.createElement('div');box.className='admin-panel admin-narrow';box.innerHTML=`<h2>Nieuw tijdelijk wachtwoord</h2><p>Dit wachtwoord wordt alleen nu getoond. Geef het veilig aan de gebruiker.</p><div class="admin-secret">${esc(pw)}</div><div class="button-row mt"><button class="btn primary" id="copy-temp">Kopieren</button><button class="btn" id="close-temp">Sluiten</button></div>`;const overlay=document.createElement('div');overlay.className='modal-overlay';overlay.append(box);document.body.append(overlay);box.querySelector('#copy-temp').onclick=()=>navigator.clipboard.writeText(pw).then(()=>toast('Wachtwoord gekopieerd.'));box.querySelector('#close-temp').onclick=()=>overlay.remove();return;}if(action==='toggle-user'){Auth.updateUser(id,{active:b.dataset.active!=='1'});render();return;}if(action==='delete-user'){if(!confirm('Account en alle lokale sportgegevens van dit account definitief verwijderen? Een eventuele Strava-koppeling wordt ook geprobeerd los te koppelen.'))return;await disconnectStravaFor(id);Auth.deleteUser(id);render();return;}if(action==='backup-export'){download(JSON.stringify(Auth.exportBundle(),null,2),'application/json','mijnloop-lokale-beheer-backup.json');toast('Backup gedownload.');return;}if(action==='backup-import'){document.getElementById('backup-file').click();return;}}catch(err){toast(err.message);}});
  document.addEventListener('change',async e=>{if(e.target.id!=='backup-file')return;const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(!confirm('Deze backup vervangt de lokale accountlijst en sportdata in deze browser. Doorgaan?'))return;const n=Auth.importBundle(data);alert(`${n} accounts geimporteerd. Je wordt uitgelogd uit beheer.`);render();}catch(err){toast(err.message);}finally{e.target.value='';}});
  render();
})();
