const {test}=require('node:test');const assert=require('node:assert/strict');
require('../core/dates.js');require('../core/planner.js');require('../core/calendar.js');require('../demo.js');const S=globalThis.SK;
const NOW=new Date('2026-10-06T10:00:00Z');
function fixture(){const s=S.freshState();s.profile={name:'Test',goal:'fit',baseWeeklyKm:25,longestKm:10,pace:6.5,raceDate:'',autoAdapt:true,timezone:'Europe/Amsterdam'};s.slots=[{id:'tue',day:1,time:'18:30',minutes:80,sport:'run',kind:'easy'},{id:'thu',day:3,time:'18:30',minutes:80,sport:'run',kind:'easy'},{id:'sun',day:6,time:'09:30',minutes:100,sport:'run',kind:'long'},{id:'sat',day:5,time:'10:00',minutes:60,sport:'strength',kind:'easy'}];S.generatePlan(s,{start:S.isoDay(NOW),now:NOW,weeks:12});const w=S.makeWorkout({id:'test-run',date:'2026-10-06',time:'07:00',title:'Voorbeeld',sport:'run',kind:'long',km:10,minutes:75},NOW);s.workouts.push(w);return s;}
function complete(s,reason='time',rpe=5){return S.logWorkout(s,'test-run',{km:5,minutes:33,rpe,reason,notes:'test'},{now:NOW});}
test('10 -> 5 km caps next comparable run, without moving fixed times',()=>{const s=fixture(),before=new Map(s.workouts.map(w=>[w.id,S.clone(w)]));complete(s);const next=s.workouts.find(w=>w.date==='2026-10-11'&&w.sport==='run');assert.equal(next.km,6);for(const w of s.workouts){assert.equal(w.date,before.get(w.id).date);assert.equal(w.time,before.get(w.id).time);}});
test('shortfall never gets added to another workout',()=>{const s=fixture(),before=new Map(s.workouts.map(w=>[w.id,w.km]));complete(s);for(const w of s.workouts.filter(w=>w.status==='planned'))assert.ok(w.km<=before.get(w.id));});
test('adaptive rerun is idempotent for distances and event sequences',()=>{const s=fixture();complete(s);const expected=s.workouts.map(w=>[w.id,w.km,w.minutes,w.sequence,w.status]);S.adaptPlan(s,{now:NOW});assert.deepEqual(s.workouts.map(w=>[w.id,w.km,w.minutes,w.sequence,w.status]),expected);});
test('completed training retains original planned distance and actual data',()=>{const s=fixture();complete(s);const w=s.workouts.find(w=>w.id==='test-run');assert.equal(w.km,10);assert.equal(w.actual.plannedKm,10);assert.equal(w.actual.km,5);});
test('editing a log does not change its originally planned distance',()=>{const s=fixture();complete(s);S.logWorkout(s,'test-run',{km:6,minutes:40,rpe:5,reason:'time'},{now:NOW});assert.equal(s.workouts.find(w=>w.id==='test-run').actual.plannedKm,10);});
test('fatigue reduces near-term running, not dates',()=>{const s=fixture();complete(s,'fatigue',8);const next=s.workouts.find(w=>w.date==='2026-10-08');assert.ok(next.km<next.baseKm);assert.equal(next.time,'18:30');});
test('pain pauses every future sport, even locked workouts',()=>{const s=fixture();s.workouts.find(w=>w.date==='2026-10-08').locked=true;complete(s,'pain');assert.equal(s.hold,true);for(const w of s.workouts.filter(w=>w.date>'2026-10-06'))assert.equal(w.status,'held');});
test('pain pause still operates with automatic adapting off',()=>{const s=fixture();s.profile.autoAdapt=false;complete(s,'pain');assert.equal(s.hold,true);assert.ok(s.workouts.some(w=>w.status==='held'));});
test('ordinary changes do not run when auto-adapt is disabled',()=>{const s=fixture();s.profile.autoAdapt=false;const before=s.workouts.filter(w=>w.id!=='test-run').map(w=>w.km);complete(s);assert.deepEqual(s.workouts.filter(w=>w.id!=='test-run').map(w=>w.km),before);});
test('rebuilding while paused cannot silently reactivate workouts',()=>{const s=fixture();complete(s,'illness');S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.ok(s.workouts.filter(w=>w.date>'2026-10-06').every(w=>w.status==='held'));});
test('resume requires validated current baseline',()=>{const s=fixture();complete(s,'pain');assert.throws(()=>S.resumePlan(s,5,10,{now:NOW}));S.resumePlan(s,15,5,{now:new Date('2026-10-07T10:00:00Z')});assert.equal(s.hold,false);assert.equal(s.profile.baseWeeklyKm,15);assert.ok(s.workouts.some(w=>w.status==='planned'));});
test('cannot record a future activity',()=>{const s=fixture(),future=s.workouts.find(w=>w.date==='2026-10-08');assert.throws(()=>S.logWorkout(s,future.id,{km:5,minutes:30,rpe:5,reason:'normal'},{now:NOW}),/toekomstige/);});
test('invalid actual distances and missing duration are rejected',()=>{for(const a of [{km:-1,minutes:30},{km:5,minutes:0},{km:NaN,minutes:20}]){const s=fixture();assert.throws(()=>S.logWorkout(s,'test-run',{...a,rpe:5,reason:'normal'},{now:NOW}));}});
test('zero kilometres and zero minutes records a skip, not success',()=>{const s=fixture();S.logWorkout(s,'test-run',{km:0,minutes:0,rpe:1,reason:'missed'},{now:NOW});assert.equal(s.workouts.find(w=>w.id==='test-run').status,'skipped');});
test('regeneration preserves completed history and stable future IDs',()=>{const s=fixture();complete(s);const history=S.clone(s.workouts.find(w=>w.id==='test-run')),ids=s.workouts.map(w=>w.id);S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.deepEqual(s.workouts.find(w=>w.id==='test-run'),history);assert.deepEqual(s.workouts.map(w=>w.id).sort(),ids.sort());});
test('planned runs calculate their own duration and respect marathon training ceiling',()=>{const s=fixture();for(const w of s.workouts.filter(w=>w.source==='plan'&&w.sport==='run')){assert.ok(w.minutes>=15);assert.ok(w.km<=32);assert.ok(w.minutes>=Math.ceil(w.km*s.profile.pace));}});
test('recurring sport slots may share a day but not the exact same start time',()=>{const s=fixture();s.slots.push({id:'ok',day:1,time:'19:00',sport:'strength'});assert.doesNotThrow(()=>S.validateProfile(s.profile,s.slots));s.slots.push({id:'bad',day:1,time:'18:30',sport:'strength'});assert.throws(()=>S.validateProfile(s.profile,s.slots),/dezelfde begintijd/);});
test('separate goals do not leak or mutate a different profile',()=>{const a=fixture(),b=fixture();b.profile.name='Other';b.profile.goal='marathon';complete(a);assert.equal(b.profile.goal,'marathon');assert.equal(b.workouts.find(w=>w.id==='test-run').actual,null);});
test('one locked workout keeps its distance on an ordinary adaptation',()=>{const s=fixture(),w=s.workouts.find(w=>w.date==='2026-10-11');w.locked=true;const n=w.km;complete(s,'fatigue',8);assert.equal(w.km,n);assert.ok(w.adaptation.includes('Vastgezet'));});
test('manual movement rejects conflicts',()=>{const s=fixture(),w=s.workouts.find(w=>w.date==='2026-10-08');assert.throws(()=>S.editWorkout(s,w.id,{date:'2026-10-10',time:'10:00'},{now:NOW}),/overlap/);});
test('cancelled events remain in data with increased sequence',()=>{const s=fixture(),w=s.workouts.find(w=>w.date==='2026-10-08');S.cancelWorkout(s,w.id,{now:NOW});assert.equal(w.status,'cancelled');assert.equal(w.sequence,1);});
test('date math treats Monday as week start and handles year boundaries',()=>{assert.equal(S.monday('2026-10-04'),'2026-09-28');assert.equal(S.addDays('2026-12-31',1),'2027-01-01');});
test('Amsterdam calendar converts summer and winter time correctly',()=>{assert.equal(S.zonedInstant('2026-10-24','18:30').toISOString(),'2026-10-24T16:30:00.000Z');assert.equal(S.zonedInstant('2026-10-26','18:30').toISOString(),'2026-10-26T17:30:00.000Z');});
test('nonexistent clock time during spring DST is rejected',()=>{assert.throws(()=>S.zonedInstant('2027-03-28','02:30'),/zomertijd/);});
test('ICS uses stable IDs and event revision numbers',()=>{const s=fixture(),w=s.workouts.find(w=>w.date==='2026-10-08');const before=S.calendarText(s,{owner:'test',now:NOW});S.editWorkout(s,w.id,{time:'20:30'},{now:NOW});const after=S.calendarText(s,{owner:'test',now:NOW});assert.ok(before.includes(`UID:${w.id}.test@sportkompas`));assert.ok(after.includes(`UID:${w.id}.test@sportkompas`));assert.ok(after.includes('SEQUENCE:1'));});
test('minimal calendar never includes private information',()=>{const s=fixture();s.profile.name='PRIVATE_PERSON';complete(s,'pain');const w=s.workouts.find(w=>w.id==='test-run');w.title='PRIVATE_TITLE';w.actual.notes='PRIVATE_NOTE';const ics=S.calendarText(s,{minimal:true,now:NOW});for(const value of ['PRIVATE_PERSON','PRIVATE_TITLE','PRIVATE_NOTE','reason:','rpe:'])assert.ok(!ics.includes(value));assert.ok(ics.includes('SUMMARY:Sporttraining'));});
test('calendar cancellations and safety pauses are exported as CANCELLED',()=>{const s=fixture();complete(s,'pain');const ics=S.calendarText(s,{now:NOW});assert.ok(ics.includes('STATUS:CANCELLED'));});
test('ICS prevents multiline injection and folds at 75 UTF-8 bytes',()=>{const escaped=S.escapeICS('Hallo\nATTENDEE:hack@example.com;test,\\');assert.ok(!escaped.includes('\n'));const folded=S.foldLine('\u00e9'.repeat(90));for(const line of folded.split('\r\n'))assert.ok(Buffer.byteLength(line)<=75);});
test('unknown and duplicate workout structures are rejected',()=>{const s=fixture();s.workouts.push(S.clone(s.workouts[0]));assert.throws(()=>S.validateState(s),/Dubbele/);});
test('demo is valid and contains a testable 10 kilometre run',()=>{const s=S.demoState(NOW);assert.ok(S.validateState(s));assert.ok(s.workouts.some(w=>w.km===10&&w.date==='2026-10-06'&&w.status==='planned'));});
test('browser and edge calendar implementations match byte for byte',()=>{const fs=require('node:fs'),path=require('node:path');for(const f of ['dates.js','calendar.js'])assert.equal(fs.readFileSync(path.join(__dirname,'../core',f),'utf8'),fs.readFileSync(path.join(__dirname,'../supabase/functions/_shared',f),'utf8'));});
test('moved recurring workout is not duplicated on regeneration',()=>{const s=fixture(),w=s.workouts.find(w=>w.date==='2026-10-08');const id=w.id;S.editWorkout(s,id,{date:'2026-10-09',time:'18:30'},{now:NOW});S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.equal(s.workouts.filter(w=>w.id===id).length,1);assert.equal(s.workouts.find(w=>w.id===id).date,'2026-10-09');assert.equal(s.workouts.filter(w=>w.date==='2026-10-08'&&w.status==='planned').length,0);});
test('time-only manual changes remain fixed after regenerating',()=>{const s=fixture(),w=s.workouts.find(w=>w.date==='2026-10-08');S.editWorkout(s,w.id,{time:'20:30'},{now:NOW});S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.equal(s.workouts.filter(x=>x.date==='2026-10-08'&&x.status==='planned').length,1);assert.equal(s.workouts.find(x=>x.id===w.id).time,'20:30');});
test('newly generated slots never overlap existing manual sports',()=>{const s=fixture();s.workouts=s.workouts.filter(w=>w.date!=='2026-10-08');s.workouts.push(S.makeWorkout({date:'2026-10-08',time:'18:30',sport:'padel',title:'Manual',minutes:60},NOW));S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.equal(s.workouts.filter(w=>w.date==='2026-10-08'&&w.status==='planned').length,1);assert.ok(s.adjustments[0].detail.includes('overlap'));});
test('marathon goal builds long runs toward December and tapers before race',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:25,longestKm:10,pace:6.2,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:12};s.slots=[{id:'tue2',day:1,time:'18:30',minutes:90,sport:'run',kind:'easy'},{id:'thu2',day:3,time:'18:30',minutes:90,sport:'run',kind:'easy'},{id:'sun2',day:6,time:'09:00',minutes:240,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});const longs=s.workouts.filter(w=>w.source==='plan'&&w.kind==='long'&&w.status==='planned');const oct=longs.find(w=>w.date==='2026-10-11'),dec=longs.find(w=>w.date==='2026-12-13'),taper=longs.find(w=>w.date==='2026-12-27');assert.ok(dec.km>oct.km+10);assert.ok(taper.km<dec.km);});
test('race date is included even when nominal horizon would stop a few days early',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:25,longestKm:10,pace:6.2,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:12};s.slots=[{id:'sun3',day:6,time:'09:00',minutes:240,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});const race=s.workouts.find(w=>w.source==='goal');assert.equal(race.date,'2026-12-31');assert.equal(race.km,42.2);assert.ok(s.planEnd>='2026-12-31');});
test('offline week target remains bounded by gradual growth',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:20,longestKm:8,pace:6.2,autoAdapt:true,timezone:'Europe/Amsterdam',horizon:12,planMode:'goal'};const t=S.targetForWeek(p,5,'2026-10-05',13);assert.ok(t.weeklyKm<=90);assert.ok(t.longKm<=32);assert.ok(t.weeklyKm>=20);});

test('race date controls an exact eight-week build window',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-01',baseWeeklyKm:24,longestKm:10,pace:6.2,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:24};s.slots=[{id:'a',day:1,time:'18:30',minutes:90,sport:'run',kind:'easy'},{id:'b',day:3,time:'18:30',minutes:90,sport:'run',kind:'easy'},{id:'c',day:6,time:'09:00',minutes:240,sport:'run',kind:'long'}];const start='2026-10-06';assert.equal(S.goalWeeks(s.profile,start),8);S.generatePlan(s,{start,now:NOW,weeks:24});assert.equal(s.planEnd,'2026-12-01');const longs=s.workouts.filter(w=>w.source==='plan'&&w.kind==='long'&&w.status==='planned');assert.ok(Math.max(...longs.map(w=>w.km))>longs[0].km);assert.ok(Math.max(...longs.map(w=>w.km))>=20);});
test('race date controls an eleven-week build and reaches a stronger pre-marathon peak when baseline allows',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-22',baseWeeklyKm:30,longestKm:12,pace:6.0,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:8};s.slots=[{id:'a2',day:1,time:'18:30',minutes:100,sport:'run',kind:'easy'},{id:'b2',day:3,time:'18:30',minutes:100,sport:'run',kind:'easy'},{id:'c2',day:6,time:'09:00',minutes:260,sport:'run',kind:'long'}];const start='2026-10-06';assert.equal(S.goalWeeks(s.profile,start),11);S.generatePlan(s,{start,now:NOW,weeks:8});assert.equal(s.planEnd,'2026-12-22');const longs=s.workouts.filter(w=>w.source==='plan'&&w.kind==='long'&&w.status==='planned');assert.ok(Math.max(...longs.map(w=>w.km))>=24);});
test('changing goal date cancels the old future goal event and creates only the new active goal',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:30,longestKm:12,pace:6.0,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:12};s.slots=[{id:'longx',day:6,time:'09:00',minutes:300,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});const old=s.workouts.find(w=>w.source==='goal'&&w.date==='2026-12-31');assert.equal(old.status,'planned');s.profile.raceDate='2027-01-17';S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.equal(old.status,'cancelled');const active=s.workouts.filter(w=>w.source==='goal'&&w.status==='planned');assert.equal(active.length,1);assert.equal(active[0].date,'2027-01-17');});
test('removing a goal date cancels an old future goal event',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:30,longestKm:12,pace:6.0,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:12};s.slots=[{id:'longy',day:6,time:'09:00',minutes:300,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});s.profile.raceDate='';s.profile.goal='fit';S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.equal(s.workouts.find(w=>w.source==='goal'&&w.date==='2026-12-31').status,'cancelled');});
test('planned marathon training runs never exceed 32 km while race day may be 42.2 km',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2027-03-28',baseWeeklyKm:65,longestKm:28,pace:5.0,autoAdapt:true,timezone:'Europe/Amsterdam',horizon:24};s.slots=[{id:'e1',day:1,time:'18:00',minutes:120,sport:'run',kind:'easy'},{id:'e2',day:3,time:'18:00',minutes:120,sport:'run',kind:'easy'},{id:'l1',day:6,time:'08:00',minutes:300,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:24});const training=s.workouts.filter(w=>w.source==='plan'&&w.sport==='run'&&w.status==='planned');assert.ok(training.length>0);assert.ok(Math.max(...training.map(w=>w.km))<=32);const race=s.workouts.find(w=>w.source==='goal'&&w.status==='planned');assert.equal(race.km,42.2);});
test('rebuilding restores a manually cancelled current goal event',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:30,longestKm:12,pace:6.0,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:12};s.slots=[{id:'longrestore',day:6,time:'09:00',minutes:300,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});const race=s.workouts.find(w=>w.source==='goal'&&w.date==='2026-12-31');S.cancelWorkout(s,race.id,{now:NOW});assert.equal(race.status,'cancelled');S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:12});assert.equal(race.status,'planned');assert.equal(race.km,42.2);});

test('reset coach history clears only assessments and preserves training data',()=>{const s=fixture();complete(s);assert.ok(s.adjustments.length>0);const workouts=JSON.stringify(s.workouts);const profile=JSON.stringify(s.profile);S.resetCoachHistory(s);assert.equal(s.adjustments.length,0);assert.equal(JSON.stringify(s.workouts),workouts);assert.equal(JSON.stringify(s.profile),profile);});

test('distant goal stays in base before entering the final 52-week goal model',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2028-01-01',baseWeeklyKm:30,longestKm:12,pace:6,autoAdapt:true,timezone:'Europe/Amsterdam',horizon:12,planMode:'goal'};const t0=S.targetForWeek(p,0,'2026-10-05',52);assert.equal(t0.phase,'basis');assert.ok(t0.weeklyKm>=30);assert.equal(t0.modelWeeks,52);});

test('legacy extra profile fields do not change the local target curve',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2026-12-22',baseWeeklyKm:30,longestKm:12,pace:6,autoAdapt:true,timezone:'Europe/Amsterdam',horizon:12,legacyStrategy:{weeks:[{index:3,weeklyKm:90,longKm:32}]}};const a=S.targetForWeek(p,3,'2026-10-05',11);const b=S.targetForWeek({...p,legacyStrategy:null},3,'2026-10-05',11);assert.deepEqual(a,b);});

test('marathon offline long-run target never exceeds 32 km',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2027-04-20',baseWeeklyKm:80,longestKm:30,pace:5,autoAdapt:true,aiMode:false,timezone:'Europe/Amsterdam',horizon:12};for(let i=0;i<30;i++)assert.ok(S.targetForWeek(p,i,'2026-10-05',30).longKm<=32);});


test('offline models exist for every goal and every duration from 4 through 52 weeks',()=>{for(const goal of ['fit','5k','10k','half','marathon'])for(let weeks=4;weeks<=52;weeks++){const model=S.OFFLINE_MODELS[goal][weeks];assert.equal(model.length,weeks);assert.equal(model[0].index,0);assert.equal(model.at(-1).index,weeks-1);}});
test('fixed planning supports exactly 4 and 52 weeks without a goal date',()=>{for(const weeks of [4,52]){const s=S.freshState();s.profile={name:'Runner',goal:'10k',raceDate:'',baseWeeklyKm:20,longestKm:8,pace:6.5,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'fixed',horizon:weeks};s.slots=[{id:'short',day:1,time:'18:00',minutes:60,sport:'run',kind:'short'},{id:'long',day:6,time:'09:00',minutes:120,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks});assert.equal(S.planWindow(s.profile,'2026-10-06').weeks,weeks);assert.ok(S.daysBetween('2026-10-06',s.planEnd)>=weeks*7-7);}});
test('goal planning uses the goal date while fixed planning ignores it for the horizon',()=>{const p={name:'Runner',goal:'10k',raceDate:'2026-12-22',baseWeeklyKm:20,longestKm:8,pace:6.5,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'goal',horizon:6};assert.equal(S.planWindow(p,'2026-10-06').toGoal,11);const fixed=S.planWindow({...p,planMode:'fixed',horizon:6},'2026-10-06');assert.equal(fixed.weeks,6);assert.equal(fixed.toGoal,null);});
test('short long and interval roles are preserved in generated schedule',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'10k',raceDate:'',baseWeeklyKm:24,longestKm:9,pace:6.2,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'fixed',horizon:8};s.slots=[{id:'short',day:1,time:'18:00',minutes:70,sport:'run',kind:'short'},{id:'int',day:3,time:'18:00',minutes:75,sport:'run',kind:'interval'},{id:'long',day:6,time:'09:00',minutes:130,sport:'run',kind:'long'}];S.generatePlan(s,{start:'2026-10-06',now:NOW,weeks:8});const runs=s.workouts.filter(w=>w.source==='plan'&&w.status==='planned');assert.ok(runs.some(w=>w.kind==='short'));assert.ok(runs.some(w=>w.kind==='long'));const intervals=runs.filter(w=>w.kind==='interval');assert.ok(intervals.length>0);assert.ok(intervals.every(w=>w.interval&&w.interval.summary&&w.interval.detail));});
test('a comfortable positive streak can raise the next comparable easy run only modestly',()=>{const s=fixture();const future=s.workouts.find(w=>w.date==='2026-10-08'&&w.sport==='run');future.kind='short';future.baseKm=8;future.km=8;const a=S.makeWorkout({id:'good1',date:'2026-10-01',time:'07:00',sport:'run',kind:'short',title:'Good 1',km:6,minutes:40,status:'done'},NOW);a.actual={km:6.4,minutes:40,rpe:5,reason:'normal',notes:'',plannedKm:6,plannedMinutes:40,loggedAt:'2026-10-01T08:00:00Z'};const b=S.makeWorkout({id:'good2',date:'2026-10-04',time:'07:00',sport:'run',kind:'short',title:'Good 2',km:6,minutes:40,status:'done'},NOW);b.actual={km:6.3,minutes:40,rpe:5,reason:'normal',notes:'',plannedKm:6,plannedMinutes:40,loggedAt:'2026-10-04T08:00:00Z'};s.workouts.push(a,b);S.adaptPlan(s,{now:NOW});assert.ok(future.km>8);assert.ok(future.km<=8.3);});
test('interval prescription scales down for a short session',()=>{const p={goal:'5k',pace:6.5};const t={phase:'opbouw',modelIndex:2};const x=S.intervalPrescription(p,t,2,4.8);assert.match(x.summary,/1 min/);assert.match(x.detail,/inlopen/);});
test('at most one long day and one interval day are accepted',()=>{const p={name:'Runner',goal:'10k',raceDate:'',baseWeeklyKm:20,longestKm:8,pace:6.5,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'fixed',horizon:8};const base=[{id:'a',day:1,time:'18:00',minutes:60,sport:'run',kind:'long'},{id:'b',day:3,time:'18:00',minutes:60,sport:'run',kind:'long'}];assert.throws(()=>S.validateProfile(p,base),/maximaal een lange/);const ints=[{id:'a',day:1,time:'18:00',minutes:60,sport:'run',kind:'interval'},{id:'b',day:3,time:'18:00',minutes:60,sport:'run',kind:'interval'}];assert.throws(()=>S.validateProfile(p,ints),/maximaal een intervaldag/);});

test('Strava-style import merges onto planned run and does not auto-adapt until confirmed',()=>{const s=fixture();const target=s.workouts.find(w=>w.date==='2026-10-08'&&w.sport==='run');const beforeKm=target.km;const r=S.mergeExternalRuns(s,[{provider:'strava',id:'12345',date:'2026-10-08',time:'18:31',name:'Avondloop',distanceKm:7.2,movingSeconds:2700,averagePaceSeconds:375,bestEfforts:[{name:'5k',distanceKm:5,seconds:1800}]}],{now:new Date('2026-10-08T20:00:00Z')});assert.equal(r.imported,1);assert.equal(target.status,'done');assert.equal(target.actual.km,7.2);assert.equal(target.actual.needsReview,true);assert.equal(target.km,beforeKm);assert.equal(target.external.provider,'strava');});

test('duplicate external import updates instead of duplicating',()=>{const s=fixture();const a={provider:'strava',id:'999',date:'2026-10-03',time:'09:00',name:'Run',distanceKm:6,movingSeconds:2100,bestEfforts:[]};S.mergeExternalRuns(s,[a],{now:NOW});const count=s.workouts.length;S.mergeExternalRuns(s,[{...a,distanceKm:6.1}],{now:new Date('2026-10-07T10:00:00Z')});assert.equal(s.workouts.length,count);assert.equal(s.workouts.find(w=>w.external?.providerId==='999').actual.km,6.1);});

test('personal records prefer exact imported best efforts',()=>{const s=fixture();S.mergeExternalRuns(s,[{provider:'strava',id:'pr1',date:'2026-10-03',time:'09:00',name:'Run',distanceKm:12,movingSeconds:3900,bestEfforts:[{name:'5k',distanceKm:5,seconds:1450},{name:'10k',distanceKm:10,seconds:3050}]}],{now:NOW});const prs=S.personalRecords(s);const five=prs.records.find(x=>x.label==='5 km');assert.equal(five.seconds,1450);assert.equal(five.estimated,false);const ten=prs.records.find(x=>x.label==='10 km');assert.equal(ten.seconds,3050);});

test('external import preserves wearable metrics when supplied',()=>{const s=fixture();S.mergeExternalRuns(s,[{provider:'strava',id:'wear1',date:'2026-10-03',time:'09:00',name:'Garmin Run',distanceKm:8,movingSeconds:2880,deviceName:'Garmin fēnix 7',elevationGain:42,averageHeartrate:151,maxHeartrate:176,averageCadence:82,bestEfforts:[]}],{now:NOW});const w=s.workouts.find(x=>x.external?.providerId==='wear1');assert.equal(w.external.deviceName,'Garmin fēnix 7');assert.equal(w.external.averageHeartrate,151);assert.equal(w.external.maxHeartrate,176);assert.equal(w.external.averageCadence,82);assert.equal(w.external.elevationGain,42);});

test('notification defaults enable upcoming and pending attention categories',()=>{const s=S.freshState();const n=S.notificationSettings(s);assert.equal(n.enabled,true);assert.equal(n.upcoming,true);assert.equal(n.pending,true);assert.equal(n.upcomingHours,4);});

test('upcoming training becomes an attention item inside configured lead time',()=>{const s=fixture();s.notifications={...S.notificationDefaults,upcomingHours:4,pending:false};const items=S.attentionItems(s,new Date('2026-10-06T14:00:00Z'));const item=items.find(x=>x.category==='upcoming'&&x.workoutId!=='test-run');assert.ok(item);});

test('past planned training becomes a pending-registration attention item',()=>{const s=fixture();s.notifications={...S.notificationDefaults,upcoming:false,pending:true,pendingDelayMinutes:30};const items=S.attentionItems(s,NOW);const item=items.find(x=>x.category==='pending'&&x.workoutId==='test-run');assert.ok(item);assert.match(item.title,/invullen/i);});

test('disabled notification categories do not contribute to attention count',()=>{const s=fixture();s.notifications={...S.notificationDefaults,upcoming:false,pending:false};assert.equal(S.attentionItems(s,NOW).length,0);s.notifications.enabled=false;s.notifications.upcoming=true;s.notifications.pending=true;assert.equal(S.attentionItems(s,NOW).length,0);});


test('goal window uses the requested eight-week model instead of adding a calendar week',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2026-12-01',baseWeeklyKm:24,longestKm:10,pace:6.2,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'goal',horizon:24};const t=S.targetForWeek(p,4,'2026-10-05',8);assert.equal(t.modelWeeks,8);assert.equal(t.modelIndex,4);assert.equal(t.phase,'piek');});

test('run slots need only a start time and generated duration grows with the plan',()=>{const s=S.freshState();s.profile={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:30,longestKm:12,pace:6,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'goal',horizon:12};s.slots=[{id:'short',day:1,time:'18:00',sport:'run',kind:'short'},{id:'longgrow',day:6,time:'09:00',sport:'run',kind:'long'}];assert.doesNotThrow(()=>S.validateProfile(s.profile,s.slots));S.generatePlan(s,{start:'2026-10-07',now:new Date('2026-10-07T06:00:00Z'),weeks:13});const longs=s.workouts.filter(w=>w.source==='plan'&&w.kind==='long'&&w.status==='planned');const peak=longs.reduce((a,b)=>a.km>b.km?a:b);assert.ok(peak.km>=30);assert.ok(peak.minutes>=Math.ceil(peak.km*s.profile.pace));assert.ok(peak.km<=32);});

test('thirteen-week marathon model reaches 32 km peak when baseline and time allow',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2026-12-31',baseWeeklyKm:30,longestKm:12,pace:6,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'goal',horizon:13};const values=Array.from({length:13},(_,i)=>S.targetForWeek(p,i,'2026-10-05',13));assert.equal(Math.max(...values.map(x=>x.longKm)),32);const peak=values.find(x=>x.longKm===32);assert.equal(peak.phase,'piek');assert.ok(values.filter(x=>x.phase==='taper').every(x=>x.longKm<32));});

test('short preparation builds upward but does not force 32 km from a low baseline',()=>{const p={name:'Runner',goal:'marathon',raceDate:'2026-12-01',baseWeeklyKm:24,longestKm:10,pace:6.2,autoAdapt:true,timezone:'Europe/Amsterdam',planMode:'goal',horizon:8};const values=Array.from({length:8},(_,i)=>S.targetForWeek(p,i,'2026-10-05',8));const max=Math.max(...values.map(x=>x.longKm));assert.ok(max>=20);assert.ok(max<32);});
